array creation methods:
 
 * `np.zeros()`, `np.ones()`, `np.full()`, `np.eye()`, `np.arange()`, `np.linspace()`
 
 * `np.empty()`, `np.zeros_like()`, `np.ones_like()`, `np.full_like()`
 
 

In [ ]:
import numpy as np
# 1d array zeros
arr=np.zeros(3,dtype=int)
print(arr)
print('------------------')
# 2d array zeros
arr=np.zeros((2,3),dtype=int)
print(arr)

[0 0 0]
------------------
[[0 0 0]
 [0 0 0]]


In [8]:
arr2=np.ones(2,dtype=int)
print(arr2)
arr3=np.ones((2,3),dtype=int)
print(arr3)

[1 1]
[[1 1 1]
 [1 1 1]]


In [10]:
# identity matrix
arr4=np.eye(4,dtype=int)
print(arr4)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [12]:
# arrange
arr5=np.arange(0,10,3)
print(arr5)

[0 3 6 9]


In [13]:
# full
arr6=np.full((2,5),7)
print(arr6)

[[7 7 7 7 7]
 [7 7 7 7 7]]
